// <auto-generated />
using Handmade.Service.EmbroideryAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Handmade.Service.EmbroideryAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Handmade.Service.EmbroideryAPI.Models.Embroidery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Prix")
                        .HasColumnType("double");

                    b.HasKey("EmbroideryId");

                    b.ToTable("Embroideries");

                    b.HasData(
                        new
                        {
                            EmbroideryId = 1,
                            CategoryName = "categorie1",
                            EmbroideryName = "ChaiseBoisMassif",
                            ImageURL = "1.jpg",
                            Price = 15.0
                        },
                        new
                        {
                            EmbroideryId = 2,
                            CategoryName = "categorie1",
                            EmbroideryName = "ChaiseBoisMassif",
                            ImageURL = "1.jpg",
                            Price = 15.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
